name: C/C++ CI

on:
  push:
    branches: [ EVM ]
  pull_request:
    branches: [ EVM ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.0
      with:
        cmake-version: '3.16.x'
    - name: configure
      run: mkdir build && cd build && cmake -DLLVM_TARGETS_TO_BUILD=EVM -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=EVM ..
    - name: make
      run: make -j4
